config/routes.rb
Rails.application.routes.draw do
  resources :suppliers

  resources :mytests

  get 'landings/index'

  resources :guitars 

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/guitar.rb
class Guitar < ActiveRecord::Base
  belongs_to :guitar_rack
end

app/models/guitar_rack.rb
class GuitarRack < ActiveRecord::Base
  has_many :guitars
end

app/models/mytest.rb
class Mytest < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController
  before_action :set_guitar, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @guitars = Guitar.all
    respond_with(@guitars)
  end

  def show
    respond_with(@guitar)
  end

  def new
    @guitar = Guitar.new
    respond_with(@guitar)
  end

  def edit
  end

  def create
    @guitar = Guitar.new(guitar_params)
    @guitar.save
    respond_with(@guitar)
  end

  def update
    @guitar.update(guitar_params)
    respond_with(@guitar)
  end

  def destroy
    @guitar.destroy
    respond_with(@guitar)
  end

  private
    def set_guitar
      @guitar = Guitar.find(params[:id])
    end

    def guitar_params
      params[:guitar].permit(:name, :make, :color, :mrp)
    end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/mytests_controller.rb
class MytestsController < ApplicationController
  before_action :set_mytest, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @mytests = Mytest.all
    respond_with(@mytests)
  end

  def show
    respond_with(@mytest)
  end

  def new
    @mytest = Mytest.new
    respond_with(@mytest)
  end

  def edit
  end

  def create
    @mytest = Mytest.new(mytest_params)
    @mytest.save
    respond_with(@mytest)
  end

  def update
    @mytest.update(mytest_params)
    respond_with(@mytest)
  end

  def destroy
    @mytest.destroy
    respond_with(@mytest)
  end

  private
    def set_mytest
      @mytest = Mytest.find(params[:id])
    end

    def mytest_params
      params[:mytest]
    end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @suppliers = Supplier.all
    respond_with(@suppliers)
  end

  def show
    respond_with(@supplier)
  end

  def new
    @supplier = Supplier.new
    respond_with(@supplier)
  end

  def edit
  end

  def create
    @supplier = Supplier.new(supplier_params)
    @supplier.save
    respond_with(@supplier)
  end

  def update
    @supplier.update(supplier_params)
    respond_with(@supplier)
  end

  def destroy
    @supplier.destroy
    respond_with(@supplier)
  end

  private
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    def supplier_params
      params.require(:supplier).permit(:name, :item_supplies)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/mytests_helper.rb
module MytestsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/elements/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Sandesh Guitar Shop", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">
    <!-- /.dropdown -->
    <li class="dropdown">

      <ul class="nav navbar-nav navbar-right">
        <% if defined?(Devise) %>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
        <% end %>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

  <%= render partial: "elements/sidebar" %>
  <!-- /.navbar-static-side -->
</nav>

app/views/elements/_sidebar.html.erb
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">

        <li>
          <%= link_to root_path do %>
            <i class="fa fa-dashboard fa-fw"></i> Dashboard
          <% end %>
        </li>

        <li>
          <%= link_to guitars_path do %>
            <i class="fa fa-cogs fa-fw"></i> Stocks
          <% end %>
        </li>

      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>

app/views/guitars/_form.html.erb
<%= simple_form_for(@guitar) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
	<%= f.input :name, label_html: { class: 'my_class' } %>
	<%= f.input :make, label_html: { class: 'my_class' } %>
	<%= f.input :color, label_html: { class: 'my_class' } %>
	<%= f.input :mrp, label_html: { class: 'my_class' } %>
</div>

<div class="form-actions">
	<%= f.button :submit %>
</div>
<% end %>

app/views/guitars/edit.html.erb
<% content_for :page_header do %>
	Edit guitar
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @guitar %> |
<%= link_to 'Back', guitars_path %>

app/views/guitars/index.html.erb
<% content_for :page_header do %>
	List of guitars
<% end %>

<table class="table table-hover">
	<thead>
		<tr>
			<th>Name</th>
			<th>Make</th>
			<th>Color</th>
			<th>Mrp</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @guitars.each do |guitar| %> 
		<tr>
			<td><%= guitar.name%></td>
			<td><%= guitar.make%></td>
			<td><%= guitar.color%></td>
			<td><%= guitar.mrp%></td>
			<td class='pull-right'>
				<%= link_to new_guitar_path do %>
					<i class="fa fa-plus pull-right"></i>
				<% end %>
			</td>
			<td class='pull-right'>
				<%= link_to edit_guitar_path(guitar) do %>
					<i class="fa fa-pencil pull-right"></i>
				<% end %>
			</td>
			<td class='pull-right'>
				<%= link_to guitar, method: :delete, data:{confirm: "Delete this contact?"} do %>
					<i class="fa fa-trash"></i>
				<% end %>
			</td>

			</tr>
		<% end %>
	</tbody>
</table>

app/views/guitars/new.html.erb
<% content_for :page_header do %>
	Add a guitar
<% end %>

<%= render 'form' %>

<%= link_to 'Back', guitars_path %>

app/views/guitars/show.html.erb
<% content_for :page_header do %>
	Guitar
<% end %>

<p id="notice"><%= notice %></p>

<%= @guitar.name%>

<%= link_to 'Edit', edit_guitar_path(@guitar) %> |
<%= link_to 'Back', guitars_path %>

app/views/landings/index.html.erb
<% content_for :page_header do %>
	Dashboard
<% end %>
<!-- /.row -->
<div class="row">
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-shopping-cart fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">Purchase</div>

					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<span class="pull-left">View Details</span>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-green">
			<a href="#">
				<div class="panel-heading">
					<div class="row">
						<div class="col-xs-3">
							<i class="fa fa-info  fa-5x"></i>
						</div>
						<div class="col-xs-9 text-right">
							<div class="huge">Supplier Detail</div>

						</div>
					</div>
				</div>
			</a>
			<a href="#">
				<div class="panel-footer">
					<span class="pull-left">View Details</span>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-yellow">
			<%= link_to guitars_path do %>
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-plus fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">View Stock</div>

					</div>
				</div>
			</div>
			<% end %>
			<%= link_to new_guitar_path do %>
				<div class="panel-footer">
					<span class="pull-left">Add Guitars</span>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			<% end %>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-red">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-bar-chart fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">Sales</div>

					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<span class="pull-left">View Details</span>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SandeshGuitarShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
	<div id="wrapper">
		<%= render partial: "elements/navbar" %>
		<%= bootstrap_flash %>

		<div id="page-wrapper">
			<div class="row">
				<div class="col-lg-12">
				<h1 class="page-header"><%= yield :page_header %></h1>
				</div>
				<!-- /.col-lg-12 -->
			</div>
			<%= yield %>
		</div>
		
	</div>
</body>
</html>

app/views/mytests/_form.html.erb
<%= simple_form_for(@mytest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <%= f.input :name, label_html: { class: 'my_class' } %>
  <%= f.input :make, label_html: { class: 'my_class' } %>
  <%= f.input :color, label_html: { class: 'my_class' } %>
  <%= f.input :mrp, label_html: { class: 'my_class' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mytests/edit.html.erb
<h1>Editing mytest</h1>

<%= render 'form' %>

<%= link_to 'Show', @mytest %> |
<%= link_to 'Back', mytests_path %>

app/views/mytests/index.html.erb
<h1>Listing mytests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mytests.each do |mytest| %>
      <tr>
        <td><%= link_to 'Show', mytest %></td>
        <td><%= link_to 'Edit', edit_mytest_path(mytest) %></td>
        <td><%= link_to 'Destroy', mytest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mytest', new_mytest_path %>

app/views/mytests/new.html.erb
<h1>New mytest</h1>

<%= render 'form' %>

<%= link_to 'Back', mytests_path %>

app/views/mytests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mytest_path(@mytest) %> |
<%= link_to 'Back', mytests_path %>

app/views/suppliers/_form.html.erb
<%= simple_form_for(@supplier) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :item_supplies %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<h1>Listing suppliers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Item supplies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td><%= supplier.name %></td>
        <td><%= supplier.item_supplies %></td>
        <td><%= link_to 'Show', supplier %></td>
        <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
        <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New supplier</h1>

<%= render 'form' %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @supplier.name %>
</p>

<p>
  <strong>Item supplies:</strong>
  <%= @supplier.item_supplies %>
</p>

<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>